name: Build Android Native Library

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Build Library with Cargo
        run: cargo build --target aarch64-linux-android --release

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: libaudio_safety_engine-arm64
          path: target/aarch64-linux-android/release/
